import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

export const dynamic = 'force-dynamic';

const instructors = [
  // NSW — Sydney metro + regional
  { first_name: 'James', last_name: 'Mitchell', suburb: 'Parramatta', state: 'NSW', postcode: '2150', lat: -33.8162, lng: 151.0032, hourly_rate: 70, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Corolla', vehicle_year: 2023, languages: ['English'], bio: 'Patient instructor with 10 years experience. Specialising in test preparation for Parramatta and Hills districts.', years_experience: 10, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Parramatta', 'Westmead', 'Wentworthville', 'Merrylands', 'Granville'], service_radius_km: 12, adi_registration: 'ADI-NSW-101', gender: 'male', familiar_test_centres: ['Parramatta', 'Seven Hills'], package_options: [{ hours: 5, price: 330, label: '5-Hour Pack' }, { hours: 10, price: 620, label: '10-Hour Pack' }] },
  { first_name: 'Sofia', last_name: 'Patel', suburb: 'Liverpool', state: 'NSW', postcode: '2170', lat: -33.9218, lng: 150.9256, hourly_rate: 65, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mazda', vehicle_model: 'CX-30', vehicle_year: 2022, languages: ['English', 'Hindi', 'Gujarati'], bio: 'Multilingual instructor serving Sydney\'s south-west. Calm and methodical teaching approach.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Liverpool', 'Cabramatta', 'Fairfield', 'Bonnyrigg', 'Edmondson Park'], service_radius_km: 10, adi_registration: 'ADI-NSW-202', gender: 'female', familiar_test_centres: ['Liverpool'], package_options: [{ hours: 5, price: 310, label: 'Starter' }, { hours: 10, price: 580, label: 'Standard' }] },
  { first_name: 'Liam', last_name: 'O\'Brien', suburb: 'Newcastle', state: 'NSW', postcode: '2300', lat: -32.9283, lng: 151.7817, hourly_rate: 60, transmission: 'both', licence_types: ['car', 'motorbike'], lesson_duration_mins: 60, vehicle_make: 'Ford', vehicle_model: 'Focus', vehicle_year: 2021, languages: ['English'], bio: 'Car and motorbike instructor. 15 years experience on Newcastle roads.', years_experience: 15, dual_controls: true, specialises_anxiety: false, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Newcastle', 'Merewether', 'Charlestown', 'Mayfield', 'Wallsend'], service_radius_km: 15, adi_registration: 'ADI-NSW-303', gender: 'male', familiar_test_centres: ['Newcastle', 'Hamilton'], package_options: [{ hours: 5, price: 280, label: '5 Pack' }] },
  { first_name: 'Emma', last_name: 'Thompson', suburb: 'Bondi Junction', state: 'NSW', postcode: '2022', lat: -33.8925, lng: 151.2485, hourly_rate: 85, transmission: 'auto', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'BMW', vehicle_model: '1 Series', vehicle_year: 2023, languages: ['English', 'French'], bio: 'Premium driving instruction in Sydney\'s Eastern Suburbs. Focus on defensive driving.', years_experience: 8, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Sat'], service_suburbs: ['Bondi Junction', 'Randwick', 'Coogee', 'Paddington', 'Double Bay'], service_radius_km: 8, adi_registration: 'ADI-NSW-404', gender: 'female', familiar_test_centres: ['Botany', 'Rosebery'], package_options: [{ hours: 5, price: 400, label: 'Premium Pack' }] },
  { first_name: 'Marcus', last_name: 'Williams', suburb: 'Penrith', state: 'NSW', postcode: '2750', lat: -33.7567, lng: 150.7066, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Hyundai', vehicle_model: 'i30', vehicle_year: 2022, languages: ['English'], bio: 'Affordable lessons in Western Sydney. Great with nervous first-time drivers.', years_experience: 5, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Penrith', 'St Marys', 'Glenmore Park', 'Jamisontown', 'Kingswood'], service_radius_km: 12, adi_registration: 'ADI-NSW-505', gender: 'male', familiar_test_centres: ['Penrith'], package_options: [{ hours: 5, price: 260, label: 'Budget Pack' }, { hours: 10, price: 480, label: 'Saver Pack' }] },

  // VIC — Melbourne metro + regional
  { first_name: 'Sarah', last_name: 'Mitchell', suburb: 'Coburg', state: 'VIC', postcode: '3058', lat: -37.7441, lng: 144.9693, hourly_rate: 65, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Corolla', vehicle_year: 2022, languages: ['English'], bio: 'Friendly patient instructor with over 8 years helping nervous drivers build confidence.', years_experience: 8, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Coburg', 'Brunswick', 'Pascoe Vale', 'Glenroy', 'Fawkner'], service_radius_km: 10, adi_registration: 'ADI-847291', gender: 'female', familiar_test_centres: ['Carlton', 'Brunswick'], package_options: [{ hours: 5, price: 300, label: 'Starter Pack' }, { hours: 10, price: 550, label: 'Value Pack' }] },
  { first_name: 'James', last_name: 'Chen', suburb: 'Box Hill', state: 'VIC', postcode: '3128', lat: -37.8189, lng: 145.1251, hourly_rate: 70, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mazda', vehicle_model: 'CX-5', vehicle_year: 2023, languages: ['English', 'Mandarin', 'Cantonese'], bio: 'Bilingual instructor specialising in licence test preparation. Knows all eastern suburb test routes.', years_experience: 12, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Box Hill', 'Doncaster', 'Blackburn', 'Burwood', 'Balwyn'], service_radius_km: 15, adi_registration: 'ADI-392018', gender: 'male', familiar_test_centres: ['Burwood East', 'Carlton'], package_options: [{ hours: 5, price: 330, label: '5-Hour Pack' }, { hours: 10, price: 620, label: '10-Hour Pack' }] },
  { first_name: 'Priya', last_name: 'Sharma', suburb: 'Werribee', state: 'VIC', postcode: '3030', lat: -37.9000, lng: 144.6616, hourly_rate: 55, transmission: 'auto', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Hyundai', vehicle_model: 'i30', vehicle_year: 2021, languages: ['English', 'Hindi', 'Punjabi'], bio: 'Calm encouraging instructor making learning to drive a positive experience for all ages.', years_experience: 5, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Werribee', 'Hoppers Crossing', 'Point Cook', 'Tarneit', 'Wyndham Vale'], service_radius_km: 10, adi_registration: 'ADI-561234', gender: 'female', familiar_test_centres: ['Werribee'], package_options: [{ hours: 5, price: 260, label: '5 Lessons' }, { hours: 10, price: 490, label: '10 Lessons' }] },
  { first_name: 'Mike', last_name: 'Thompson', suburb: 'Reservoir', state: 'VIC', postcode: '3073', lat: -37.7160, lng: 145.0070, hourly_rate: 60, transmission: 'manual', licence_types: ['car'], lesson_duration_mins: 90, vehicle_make: 'Volkswagen', vehicle_model: 'Golf', vehicle_year: 2022, languages: ['English'], bio: 'Manual transmission specialist teaching proper clutch control and gear changing techniques.', years_experience: 15, dual_controls: true, specialises_anxiety: false, accepts_international: false, availability_days: ['Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Reservoir', 'Preston', 'Thornbury', 'Northcote', 'Bundoora'], service_radius_km: 10, adi_registration: 'ADI-784512', gender: 'male', familiar_test_centres: ['Carlton', 'Heidelberg'], package_options: [{ hours: 5, price: 280, label: 'Manual Pack' }, { hours: 10, price: 520, label: 'Manual Value' }] },
  { first_name: 'David', last_name: 'Nguyen', suburb: 'Footscray', state: 'VIC', postcode: '3011', lat: -37.7996, lng: 144.8995, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Camry', vehicle_year: 2020, languages: ['English', 'Vietnamese'], bio: 'Affordable lessons in the inner west. Patient with first-time drivers and test preparation.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Footscray', 'Yarraville', 'Sunshine', 'St Albans', 'Deer Park'], service_radius_km: 12, adi_registration: 'ADI-678901', gender: 'male', familiar_test_centres: ['Carlton', 'Werribee'], package_options: [{ hours: 5, price: 260, label: 'Starter' }, { hours: 10, price: 480, label: 'Standard' }] },
  { first_name: 'Anna', last_name: 'Kowalski', suburb: 'Glen Waverley', state: 'VIC', postcode: '3150', lat: -37.8788, lng: 145.1641, hourly_rate: 72, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Subaru', vehicle_model: 'Impreza', vehicle_year: 2023, languages: ['English', 'Polish'], bio: 'Detail-oriented instructor focusing on building safe driving habits from day one. High pass rate.', years_experience: 9, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Sat'], service_suburbs: ['Glen Waverley', 'Mount Waverley', 'Clayton', 'Oakleigh', 'Chadstone'], service_radius_km: 10, adi_registration: 'ADI-789012', gender: 'female', familiar_test_centres: ['Burwood East'], package_options: [{ hours: 5, price: 340, label: '5 Pack' }, { hours: 10, price: 640, label: '10 Pack' }] },
  { first_name: 'Carlos', last_name: 'Rivera', suburb: 'Craigieburn', state: 'VIC', postcode: '3064', lat: -37.6033, lng: 144.9400, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Kia', vehicle_model: 'Cerato', vehicle_year: 2022, languages: ['English', 'Spanish'], bio: 'Friendly instructor serving Melbourne\'s northern growth corridor. Flexible with pickup locations.', years_experience: 4, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Craigieburn', 'Roxburgh Park', 'Epping', 'Mill Park', 'Broadmeadows'], service_radius_km: 12, adi_registration: 'ADI-456789', gender: 'male', familiar_test_centres: ['Carlton'], package_options: [{ hours: 5, price: 260, label: 'Starter' }] },
  { first_name: 'Grace', last_name: 'Brown', suburb: 'Geelong', state: 'VIC', postcode: '3220', lat: -38.1499, lng: 144.3617, hourly_rate: 58, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Yaris', vehicle_year: 2022, languages: ['English'], bio: 'Serving the Geelong region for over 6 years. Great with teens and nervous drivers.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Geelong', 'Newtown', 'Waurn Ponds', 'Grovedale', 'Highton'], service_radius_km: 15, adi_registration: 'ADI-901234', gender: 'female', familiar_test_centres: ['Geelong'], package_options: [{ hours: 5, price: 275, label: 'Geelong Pack' }] },
  { first_name: 'Ben', last_name: 'Taylor', suburb: 'Ballarat', state: 'VIC', postcode: '3350', lat: -37.5622, lng: 143.8503, hourly_rate: 50, transmission: 'both', licence_types: ['car', 'truck'], lesson_duration_mins: 60, vehicle_make: 'Holden', vehicle_model: 'Colorado', vehicle_year: 2021, languages: ['English'], bio: 'Car and light truck instruction in Ballarat and surrounding areas. Affordable rates.', years_experience: 11, dual_controls: true, specialises_anxiety: false, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Ballarat', 'Wendouree', 'Sebastopol', 'Buninyong', 'Alfredton'], service_radius_km: 20, adi_registration: 'ADI-567890', gender: 'male', familiar_test_centres: ['Ballarat'], package_options: [{ hours: 5, price: 240, label: '5 Pack' }, { hours: 10, price: 450, label: '10 Pack' }] },

  // QLD — Brisbane metro + Gold Coast + regional
  { first_name: 'Rachel', last_name: 'Wong', suburb: 'Fortitude Valley', state: 'QLD', postcode: '4006', lat: -27.4567, lng: 153.0341, hourly_rate: 72, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mazda', vehicle_model: '3', vehicle_year: 2023, languages: ['English', 'Mandarin'], bio: 'Brisbane CBD specialist. Knows all the inner-city test routes and traffic patterns.', years_experience: 9, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Fortitude Valley', 'New Farm', 'Kelvin Grove', 'Paddington', 'Bowen Hills'], service_radius_km: 8, adi_registration: 'ADI-QLD-101', gender: 'female', familiar_test_centres: ['Greenslopes', 'Chermside'], package_options: [{ hours: 5, price: 340, label: 'City Pack' }, { hours: 10, price: 640, label: 'City Value' }] },
  { first_name: 'Tom', last_name: 'Johnston', suburb: 'Chermside', state: 'QLD', postcode: '4032', lat: -27.3861, lng: 153.0311, hourly_rate: 60, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Camry', vehicle_year: 2022, languages: ['English'], bio: 'North Brisbane instructor. Patient with seniors and first-time drivers.', years_experience: 8, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Chermside', 'Aspley', 'Kedron', 'Zillmere', 'Bridgeman Downs'], service_radius_km: 12, adi_registration: 'ADI-QLD-202', gender: 'male', familiar_test_centres: ['Chermside'], package_options: [{ hours: 5, price: 290, label: 'Northside Pack' }] },
  { first_name: 'Mia', last_name: 'Roberts', suburb: 'Surfers Paradise', state: 'QLD', postcode: '4217', lat: -28.0067, lng: 153.4312, hourly_rate: 75, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Audi', vehicle_model: 'A3', vehicle_year: 2023, languages: ['English'], bio: 'Gold Coast instructor. Specialises in motorway confidence and test preparation.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Surfers Paradise', 'Broadbeach', 'Southport', 'Main Beach', 'Benowa'], service_radius_km: 10, adi_registration: 'ADI-QLD-303', gender: 'female', familiar_test_centres: ['Southport', 'Helensvale'], package_options: [{ hours: 5, price: 350, label: 'Coast Pack' }, { hours: 10, price: 660, label: 'Coast Value' }] },
  { first_name: 'Chris', last_name: 'Baker', suburb: 'Toowoomba', state: 'QLD', postcode: '4350', lat: -27.5597, lng: 151.9540, hourly_rate: 52, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Suzuki', vehicle_model: 'Swift', vehicle_year: 2021, languages: ['English'], bio: 'Toowoomba and Darling Downs instructor. Affordable lessons for all skill levels.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Toowoomba', 'Mount Lofty', 'Rangeville', 'Darling Heights', 'Wilsonton'], service_radius_km: 15, adi_registration: 'ADI-QLD-404', gender: 'male', familiar_test_centres: ['Toowoomba'], package_options: [{ hours: 5, price: 250, label: 'Regional Pack' }] },
  { first_name: 'Lily', last_name: 'Chang', suburb: 'Sunnybank', state: 'QLD', postcode: '4109', lat: -27.5800, lng: 153.0590, hourly_rate: 65, transmission: 'auto', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Honda', vehicle_model: 'HR-V', vehicle_year: 2022, languages: ['English', 'Mandarin', 'Cantonese'], bio: 'Multilingual instructor in Brisbane\'s southside. Ideal for international licence conversions.', years_experience: 5, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Sunnybank', 'Eight Mile Plains', 'Runcorn', 'Calamvale', 'Stretton'], service_radius_km: 10, adi_registration: 'ADI-QLD-505', gender: 'female', familiar_test_centres: ['Greenslopes'], package_options: [{ hours: 5, price: 310, label: 'Southside Pack' }] },
  { first_name: 'Jack', last_name: 'Dawson', suburb: 'Townsville', state: 'QLD', postcode: '4810', lat: -19.2585, lng: 146.8191, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Ford', vehicle_model: 'Focus', vehicle_year: 2021, languages: ['English'], bio: 'North Queensland instructor covering Townsville and Thuringowa. Patient and thorough.', years_experience: 10, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Townsville', 'Thuringowa', 'Kirwan', 'Aitkenvale', 'Mundingburra'], service_radius_km: 15, adi_registration: 'ADI-QLD-606', gender: 'male', familiar_test_centres: ['Townsville'], package_options: [{ hours: 5, price: 260, label: 'NQ Pack' }] },

  // WA — Perth metro
  { first_name: 'Nathan', last_name: 'Cooper', suburb: 'Joondalup', state: 'WA', postcode: '6027', lat: -31.7447, lng: 115.7668, hourly_rate: 68, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Corolla', vehicle_year: 2023, languages: ['English'], bio: 'Perth northern suburbs specialist. High first-time pass rate.', years_experience: 8, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Joondalup', 'Edgewater', 'Heathridge', 'Connolly', 'Ocean Reef'], service_radius_km: 10, adi_registration: 'ADI-WA-101', gender: 'male', familiar_test_centres: ['Joondalup'], package_options: [{ hours: 5, price: 320, label: 'Northern Pack' }, { hours: 10, price: 600, label: 'Northern Value' }] },
  { first_name: 'Aisha', last_name: 'Hassan', suburb: 'Fremantle', state: 'WA', postcode: '6160', lat: -32.0561, lng: 115.7460, hourly_rate: 65, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Hyundai', vehicle_model: 'Kona', vehicle_year: 2022, languages: ['English', 'Arabic', 'Somali'], bio: 'Multilingual instructor in Fremantle and surrounding areas. Great with nervous learners.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Fremantle', 'Hilton', 'South Fremantle', 'Hamilton Hill', 'Spearwood'], service_radius_km: 10, adi_registration: 'ADI-WA-202', gender: 'female', familiar_test_centres: ['Fremantle'], package_options: [{ hours: 5, price: 310, label: 'Fremantle Pack' }] },
  { first_name: 'Ben', last_name: 'Adams', suburb: 'Midland', state: 'WA', postcode: '6056', lat: -31.8894, lng: 116.0081, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mitsubishi', vehicle_model: 'Lancer', vehicle_year: 2021, languages: ['English'], bio: 'Serving Perth\'s eastern region and the Hills. Affordable quality instruction.', years_experience: 12, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Midland', 'Guildford', 'Mundaring', 'Kalamunda', 'Swan View'], service_radius_km: 15, adi_registration: 'ADI-WA-303', gender: 'male', familiar_test_centres: ['Midland'], package_options: [{ hours: 5, price: 260, label: 'Hills Pack' }] },
  { first_name: 'Jessica', last_name: 'Lee', suburb: 'Mandurah', state: 'WA', postcode: '6210', lat: -32.5281, lng: 115.7380, hourly_rate: 58, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mazda', vehicle_model: '2', vehicle_year: 2022, languages: ['English'], bio: 'Peel region instructor. Patient and encouraging, specialising in mature-age learners.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Mandurah', 'Pinjarra', 'Dawesville', 'Falcon', 'Greenfields'], service_radius_km: 20, adi_registration: 'ADI-WA-404', gender: 'female', familiar_test_centres: ['Mandurah'], package_options: [{ hours: 5, price: 275, label: 'Peel Pack' }] },

  // SA — Adelaide metro
  { first_name: 'Daniel', last_name: 'Smith', suburb: 'Adelaide CBD', state: 'SA', postcode: '5000', lat: -34.9285, lng: 138.6007, hourly_rate: 65, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Corolla', vehicle_year: 2023, languages: ['English'], bio: 'Adelaide city instructor. Expert in city driving, tram tracks, and test route preparation.', years_experience: 10, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Adelaide', 'North Adelaide', 'Unley', 'Norwood', 'Parkside'], service_radius_km: 8, adi_registration: 'ADI-SA-101', gender: 'male', familiar_test_centres: ['Adelaide', 'Wingfield'], package_options: [{ hours: 5, price: 310, label: 'City Pack' }, { hours: 10, price: 590, label: 'City Value' }] },
  { first_name: 'Emma', last_name: 'Clark', suburb: 'Glenelg', state: 'SA', postcode: '5045', lat: -34.9812, lng: 138.5110, hourly_rate: 62, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Volkswagen', vehicle_model: 'Polo', vehicle_year: 2022, languages: ['English'], bio: 'Coastal Adelaide instructor. Patient and thorough with all skill levels.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Glenelg', 'Brighton', 'Hove', 'Morphettville', 'Somerton Park'], service_radius_km: 8, adi_registration: 'ADI-SA-202', gender: 'female', familiar_test_centres: ['Wingfield', 'Adelaide'], package_options: [{ hours: 5, price: 295, label: 'Coastal Pack' }] },
  { first_name: 'Tony', last_name: 'Marino', suburb: 'Elizabeth', state: 'SA', postcode: '5112', lat: -34.7190, lng: 138.6736, hourly_rate: 52, transmission: 'both', licence_types: ['car', 'motorbike'], lesson_duration_mins: 60, vehicle_make: 'Suzuki', vehicle_model: 'Swift', vehicle_year: 2021, languages: ['English', 'Italian'], bio: 'Northern suburbs instructor. Car and motorbike lessons at affordable rates.', years_experience: 14, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Elizabeth', 'Munno Para', 'Smithfield', 'Davoren Park', 'Craigmore'], service_radius_km: 12, adi_registration: 'ADI-SA-303', gender: 'male', familiar_test_centres: ['Wingfield'], package_options: [{ hours: 5, price: 250, label: 'Northern Pack' }] },

  // ACT — Canberra
  { first_name: 'Kate', last_name: 'Wilson', suburb: 'Canberra City', state: 'ACT', postcode: '2601', lat: -35.2809, lng: 149.1300, hourly_rate: 68, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Subaru', vehicle_model: 'Impreza', vehicle_year: 2023, languages: ['English'], bio: 'Canberra instructor. Knows all ACT test routes including the challenging roundabout courses.', years_experience: 8, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Canberra City', 'Barton', 'Deakin', 'Kingston', 'Manuka'], service_radius_km: 12, adi_registration: 'ADI-ACT-101', gender: 'female', familiar_test_centres: ['Canberra', 'Dickson', 'Belconnen'], package_options: [{ hours: 5, price: 320, label: 'ACT Pack' }, { hours: 10, price: 600, label: 'ACT Value' }] },
  { first_name: 'Michael', last_name: 'Harris', suburb: 'Belconnen', state: 'ACT', postcode: '2617', lat: -35.2428, lng: 149.0767, hourly_rate: 62, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Camry', vehicle_year: 2022, languages: ['English'], bio: 'North Canberra instructor. Specialises in nervous drivers and test preparation.', years_experience: 9, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Belconnen', 'Aranda', 'Bruce', 'Cook', 'Hawker'], service_radius_km: 10, adi_registration: 'ADI-ACT-202', gender: 'male', familiar_test_centres: ['Belconnen', 'Canberra'], package_options: [{ hours: 5, price: 300, label: 'Belconnen Pack' }] },

  // NT — Darwin
  { first_name: 'Jake', last_name: 'Riley', suburb: 'Darwin City', state: 'NT', postcode: '0800', lat: -12.4634, lng: 130.8456, hourly_rate: 60, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Hilux', vehicle_year: 2022, languages: ['English'], bio: 'Darwin instructor experienced in tropical driving conditions and wildlife awareness.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Darwin City', 'Casuarina', 'Palmerston', 'Nightcliff', 'Fannie Bay'], service_radius_km: 15, adi_registration: 'ADI-NT-101', gender: 'male', familiar_test_centres: ['Darwin'], package_options: [{ hours: 5, price: 290, label: 'Top End Pack' }] },
  { first_name: 'Samantha', last_name: 'Cross', suburb: 'Alice Springs', state: 'NT', postcode: '0870', lat: -23.6980, lng: 133.8807, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mitsubishi', vehicle_model: 'Outlander', vehicle_year: 2021, languages: ['English'], bio: 'Central Australia instructor. Patient teaching for all ages in the Red Centre.', years_experience: 5, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Alice Springs', 'Gillen', 'Larapinta', 'Braitling', 'Mount Johns'], service_radius_km: 10, adi_registration: 'ADI-NT-202', gender: 'female', familiar_test_centres: ['Alice Springs'], package_options: [{ hours: 5, price: 265, label: 'Central Pack' }] },

  // TAS — Hobart + Launceston
  { first_name: 'Patrick', last_name: 'Murphy', suburb: 'Hobart CBD', state: 'TAS', postcode: '7000', lat: -42.8821, lng: 147.3312, hourly_rate: 62, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Hyundai', vehicle_model: 'i30', vehicle_year: 2022, languages: ['English'], bio: 'Hobart instructor specialising in hilly terrain and narrow city street navigation.', years_experience: 9, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Hobart', 'Sandy Bay', 'Battery Point', 'North Hobart', 'West Hobart'], service_radius_km: 10, adi_registration: 'ADI-TAS-101', gender: 'male', familiar_test_centres: ['Hobart', 'Mowbray'], package_options: [{ hours: 5, price: 300, label: 'Hobart Pack' }, { hours: 10, price: 560, label: 'Hobart Value' }] },
  { first_name: 'Sarah', last_name: 'Davis', suburb: 'Launceston', state: 'TAS', postcode: '7250', lat: -41.4392, lng: 147.1366, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Kia', vehicle_model: 'Rio', vehicle_year: 2021, languages: ['English'], bio: 'Northern Tasmania instructor. Friendly and patient with learners of all ages.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Launceston', 'Newnham', 'Kings Meadows', 'Prospect', 'Mowbray'], service_radius_km: 15, adi_registration: 'ADI-TAS-202', gender: 'female', familiar_test_centres: ['Launceston', 'Mowbray'], package_options: [{ hours: 5, price: 265, label: 'Tamar Pack' }] },
  { first_name: 'Tim', last_name: 'Graham', suburb: 'Devonport', state: 'TAS', postcode: '7310', lat: -41.1788, lng: 146.3607, hourly_rate: 50, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Holden', vehicle_model: 'Cruze', vehicle_year: 2021, languages: ['English'], bio: 'North-West Coast instructor serving Devonport and Burnie regions.', years_experience: 11, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Devonport', 'Burnie', 'Ulverstone', 'Wynyard', 'Penguin'], service_radius_km: 20, adi_registration: 'ADI-TAS-303', gender: 'male', familiar_test_centres: ['Devonport'], package_options: [{ hours: 5, price: 240, label: 'NW Coast Pack' }] },
];

const reviewTemplates = [
  { reviewer: 'Tom S.', rating: 5, patience: 5, comms: 5, value: 4, punctuality: 5, pass: 'passed_first' as const, text: 'Amazing instructor! Very patient and helped me pass first time.' },
  { reviewer: 'Emma W.', rating: 4, patience: 4, comms: 5, value: 4, punctuality: 5, pass: 'passed_first' as const, text: 'Great instructor, really helped with my parallel parking technique.' },
  { reviewer: 'Jack R.', rating: 5, patience: 5, comms: 5, value: 5, punctuality: 5, pass: 'passed_first' as const, text: 'Couldn\'t have asked for a better instructor. Highly recommend.' },
  { reviewer: 'Olivia P.', rating: 4, patience: 5, comms: 4, value: 3, punctuality: 4, pass: 'passed_retry' as const, text: 'Really helped me overcome my nerves after failing my first test.' },
  { reviewer: 'Liam N.', rating: 5, patience: 4, comms: 5, value: 5, punctuality: 5, pass: 'passed_first' as const, text: 'Professional, knowledgeable, and made the whole process really easy.' },
  { reviewer: 'Sophie M.', rating: 4, patience: 5, comms: 4, value: 4, punctuality: 4, pass: 'still_learning' as const, text: 'Still learning but feeling much more confident behind the wheel.' },
  { reviewer: 'Noah K.', rating: 5, patience: 5, comms: 5, value: 5, punctuality: 5, pass: 'passed_first' as const, text: 'Best driving instructor. No question.' },
  { reviewer: 'Mia C.', rating: 4, patience: 4, comms: 4, value: 4, punctuality: 5, pass: 'passed_retry' as const, text: 'Very thorough and made sure I was ready before booking my test.' },
  { reviewer: 'Ethan B.', rating: 5, patience: 5, comms: 5, value: 5, punctuality: 4, pass: 'passed_first' as const, text: 'Fantastic experience from start to finish. Highly skilled instructor.' },
  { reviewer: 'Ava L.', rating: 4, patience: 4, comms: 5, value: 4, punctuality: 5, pass: 'passed_first' as const, text: 'Clear instructions and very patient. Made learning enjoyable.' },
];

function slugify(first: string, last: string, suburb: string) {
  return `${first.toLowerCase()}-${last.toLowerCase().replace(/'/, '')}-${suburb.toLowerCase().replace(/\s+/g, '-')}`;
}

export async function GET() {
  if (!supabase) {
    return NextResponse.json({ error: 'Supabase not configured' }, { status: 500 });
  }

  // Clear existing data (FK-safe order)
  await supabase.from('listing_flags').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  await supabase.from('reviews').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  await supabase.from('search_logs').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  const { count: deleted } = await supabase.from('instructors').delete().neq('id', '00000000-0000-0000-0000-000000000000');

  const results: { instructor: string; status: string; error?: string }[] = [];

  for (const inst of instructors) {
    const slug = slugify(inst.first_name, inst.last_name, inst.suburb);

    const { error } = await supabase.from('instructors').insert({
      slug,
      ...inst,
      is_claimed: false,
      is_verified: true,
      profile_completeness: 100,
    });

    if (error) {
      results.push({ instructor: `${inst.first_name} ${inst.last_name}`, status: 'error', error: error.message });
      continue;
    }

    const { data: inserted } = await supabase.from('instructors').select('id').eq('slug', slug).single();

    if (inserted) {
      const selectedReviews = reviewTemplates.sort(() => Math.random() - 0.5).slice(0, 3 + Math.floor(Math.random() * 5));
      for (const r of selectedReviews) {
        await supabase.from('reviews').insert({
          instructor_id: inserted.id,
          reviewer_name: r.reviewer,
          reviewer_email: `${r.reviewer.toLowerCase().replace(/\s/, '')}@example.com`,
          rating_overall: r.rating,
          rating_patience: r.patience,
          rating_communication: r.comms,
          rating_value: r.value,
          rating_punctuality: r.punctuality,
          pass_outcome: r.pass,
          review_text: r.text,
          is_approved: true,
        });
      }
    }

    results.push({ instructor: `${inst.first_name} ${inst.last_name} (${inst.suburb}, ${inst.state})`, status: 'inserted' });
  }

  const inserted = results.filter((r) => r.status === 'inserted').length;
  const failed = results.filter((r) => r.status === 'error').length;

  return NextResponse.json({
    message: `Cleared ${deleted ?? 0} existing instructors. Seeded ${inserted} instructors across Australia (${failed} failed).`,
    total: inserted,
    failed,
    results,
  });
}
