import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

export const dynamic = 'force-dynamic';

const instructors = [
  // NSW — 5 instructors
  { first_name: 'Oliver', last_name: 'Hayes', suburb: 'Chatswood', state: 'NSW', postcode: '2067', lat: -33.7964, lng: 151.1837, hourly_rate: 75, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Camry', vehicle_year: 2023, languages: ['English', 'Korean'], bio: 'Patient instructor serving Sydneys lower north shore. Specialises in nervous drivers and test preparation.', years_experience: 9, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Chatswood', 'St Leonards', 'North Sydney', 'Artarmon', 'Roseville'], service_radius_km: 10, adi_registration: 'ADI-NSW-707', gender: 'male', familiar_test_centres: ['Chatswood', 'Ryde'], package_options: [{ hours: 5, price: 350, label: '5 Pack' }, { hours: 10, price: 660, label: '10 Pack' }] },
  { first_name: 'Isabella', last_name: 'Torres', suburb: 'Campbelltown', state: 'NSW', postcode: '2560', lat: -34.0658, lng: 150.8146, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mazda', vehicle_model: '2', vehicle_year: 2022, languages: ['English', 'Spanish'], bio: 'Affordable lessons in Macarthur region. Great with first-time drivers and teenagers.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Campbelltown', 'Camden', 'Narellan', 'Ingleburn', 'Macquarie Fields'], service_radius_km: 15, adi_registration: 'ADI-NSW-808', gender: 'female', familiar_test_centres: ['Campbelltown'], package_options: [{ hours: 5, price: 260, label: 'Macarthur Pack' }] },
  { first_name: 'Ethan', last_name: 'Foster', suburb: 'Gosford', state: 'NSW', postcode: '2250', lat: -33.4273, lng: 151.3417, hourly_rate: 58, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Hyundai', vehicle_model: 'i30', vehicle_year: 2021, languages: ['English'], bio: 'Central Coast instructor covering coast and hinterland. Flexible scheduling available.', years_experience: 8, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Gosford', 'Erina', 'Terrigal', 'Wyong', 'Tuggerah'], service_radius_km: 20, adi_registration: 'ADI-NSW-909', gender: 'male', familiar_test_centres: ['Gosford', 'Wyong'], package_options: [{ hours: 5, price: 270, label: 'Coast Pack' }] },
  { first_name: 'Mia', last_name: 'Bennett', suburb: 'Hurstville', state: 'NSW', postcode: '2220', lat: -33.9676, lng: 151.1010, hourly_rate: 68, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Honda', vehicle_model: 'Civic', vehicle_year: 2023, languages: ['English', 'Mandarin', 'Cantonese'], bio: 'Multilingual instructor in Sydneys St George area. High pass rate with interstate conversions.', years_experience: 7, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Hurstville', 'Kogarah', 'Rockdale', 'Beverly Hills', 'Penshurst'], service_radius_km: 8, adi_registration: 'ADI-NSW-010', gender: 'female', familiar_test_centres: ['Botany', 'Rockdale'], package_options: [{ hours: 5, price: 320, label: 'St George Pack' }, { hours: 10, price: 600, label: 'St George Value' }] },
  { first_name: 'Noah', last_name: 'Knight', suburb: 'Wagga Wagga', state: 'NSW', postcode: '2650', lat: -35.1082, lng: 147.3593, hourly_rate: 50, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Holden', vehicle_model: 'Cruze', vehicle_year: 2021, languages: ['English'], bio: 'Regional instructor serving the Riverina. Affordable rates and patient teaching style.', years_experience: 12, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Wagga Wagga', 'Tolland', 'Turvey Park', 'Glenfield Park', 'Kapooka'], service_radius_km: 20, adi_registration: 'ADI-NSW-111', gender: 'male', familiar_test_centres: ['Wagga Wagga'], package_options: [{ hours: 5, price: 240, label: 'Riverina Pack' }] },

  // VIC — 5 instructors
  { first_name: 'Charlotte', last_name: 'Wood', suburb: 'Sunbury', state: 'VIC', postcode: '3429', lat: -37.5799, lng: 144.7242, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Kia', vehicle_model: 'Cerato', vehicle_year: 2022, languages: ['English'], bio: 'Melbournes north-western suburbs specialist. Patient with learners of all ages.', years_experience: 5, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Sunbury', 'Diggers Rest', 'Bullabrook', 'Clarkefield', 'Riddells Creek'], service_radius_km: 12, adi_registration: 'ADI-123456', gender: 'female', familiar_test_centres: ['Carlton'], package_options: [{ hours: 5, price: 260, label: 'Northwest Pack' }] },
  { first_name: 'William', last_name: 'Ferguson', suburb: 'Pakenham', state: 'VIC', postcode: '3810', lat: -38.0795, lng: 145.4862, hourly_rate: 52, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Yaris', vehicle_year: 2021, languages: ['English'], bio: 'Serving Melbournes south-east growth corridor. Reliable and encouraging instruction.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Pakenham', 'Officer', 'Beaconsfield', 'Nar Nar Goon', 'Garfield'], service_radius_km: 15, adi_registration: 'ADI-234567', gender: 'male', familiar_test_centres: ['Dandenong', 'Pakenham'], package_options: [{ hours: 5, price: 250, label: 'South East Pack' }] },
  { first_name: 'Amelia', last_name: 'Ward', suburb: 'Carnegie', state: 'VIC', postcode: '3163', lat: -37.8905, lng: 145.0575, hourly_rate: 70, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mazda', vehicle_model: 'CX-30', vehicle_year: 2023, languages: ['English', 'Greek'], bio: 'Bilingual instructor in Melbournes south-east. Defensive driving focus with proven test results.', years_experience: 10, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Carnegie', 'Murrumbeena', 'Glen Huntly', 'Caulfield', 'Malvern East'], service_radius_km: 8, adi_registration: 'ADI-345678', gender: 'female', familiar_test_centres: ['Carlton', 'Burwood East'], package_options: [{ hours: 5, price: 330, label: 'Bayside Pack' }, { hours: 10, price: 620, label: 'Bayside Value' }] },
  { first_name: 'Henry', last_name: 'Turner', suburb: 'Melton', state: 'VIC', postcode: '3337', lat: -37.6832, lng: 144.5848, hourly_rate: 50, transmission: 'manual', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Ford', vehicle_model: 'Focus', vehicle_year: 2020, languages: ['English'], bio: 'Manual transmission specialist in Melbournes west. Patient teaching with a focus on proper technique.', years_experience: 14, dual_controls: true, specialises_anxiety: false, accepts_international: false, availability_days: ['Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Melton', 'Caroline Springs', 'Taylors Lakes', 'Hillside', 'Sydenham'], service_radius_km: 12, adi_registration: 'ADI-456789', gender: 'male', familiar_test_centres: ['Werribee', 'Carlton'], package_options: [{ hours: 5, price: 240, label: 'Western Pack' }] },
  { first_name: 'Sophie', last_name: 'Miller', suburb: 'Bendigo', state: 'VIC', postcode: '3550', lat: -36.7570, lng: 144.2801, hourly_rate: 53, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Suzuki', vehicle_model: 'Swift', vehicle_year: 2022, languages: ['English'], bio: 'Regional Victoria instructor serving Bendigo and the Goldfields. Great with all experience levels.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Bendigo', 'Maiden Gully', 'Eaglehawk', 'Kangaroo Flat', 'Strathdale'], service_radius_km: 15, adi_registration: 'ADI-567890', gender: 'female', familiar_test_centres: ['Bendigo'], package_options: [{ hours: 5, price: 250, label: 'Goldfields Pack' }] },

  // QLD — 4 instructors
  { first_name: 'Lucas', last_name: 'Anderson', suburb: 'Coorparoo', state: 'QLD', postcode: '4151', lat: -27.4938, lng: 153.0586, hourly_rate: 68, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Subaru', vehicle_model: 'XV', vehicle_year: 2023, languages: ['English'], bio: 'Brisbane inner-south instructor. High first-time pass rate with thorough test preparation.', years_experience: 8, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Coorparoo', 'Camp Hill', 'Carina', 'Norman Park', 'Greenslopes'], service_radius_km: 8, adi_registration: 'ADI-QLD-111', gender: 'male', familiar_test_centres: ['Greenslopes'], package_options: [{ hours: 5, price: 320, label: 'Inner South' }, { hours: 10, price: 600, label: 'Inner South Value' }] },
  { first_name: 'Harper', last_name: 'Collins', suburb: 'Cairns', state: 'QLD', postcode: '4870', lat: -16.9203, lng: 145.7704, hourly_rate: 58, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Corolla', vehicle_year: 2022, languages: ['English', 'Japanese'], bio: 'Far North Queensland instructor. Experienced with wet season driving conditions and tourist-heavy areas.', years_experience: 9, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Cairns', 'Port Douglas', 'Mareeba', 'Smithfield', 'Trinity Park'], service_radius_km: 25, adi_registration: 'ADI-QLD-222', gender: 'female', familiar_test_centres: ['Cairns', 'Mareeba'], package_options: [{ hours: 5, price: 275, label: 'FNQ Pack' }] },
  { first_name: 'Owen', last_name: 'Mitchell', suburb: 'Ipswich', state: 'QLD', postcode: '4305', lat: -27.6150, lng: 152.7611, hourly_rate: 54, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Hyundai', vehicle_model: 'Elantra', vehicle_year: 2021, languages: ['English'], bio: 'Ipswich and western corridor instructor. Affordable lessons for learner drivers of all ages.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Ipswich', 'Springfield', 'Goodna', 'Redbank', 'Karalee'], service_radius_km: 12, adi_registration: 'ADI-QLD-333', gender: 'male', familiar_test_centres: ['Ipswich'], package_options: [{ hours: 5, price: 255, label: 'Ipswich Pack' }] },
  { first_name: 'Evelyn', last_name: 'Grant', suburb: 'Bundaberg', state: 'QLD', postcode: '4670', lat: -24.8668, lng: 152.3481, hourly_rate: 50, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mitsubishi', vehicle_model: 'Lancer', vehicle_year: 2021, languages: ['English'], bio: 'Wide Bay region instructor serving Bundaberg and the Burnett. Patient and encouraging.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Bundaberg', 'Bargara', 'Childers', 'Gin Gin', 'Montalban'], service_radius_km: 20, adi_registration: 'ADI-QLD-444', gender: 'female', familiar_test_centres: ['Bundaberg'], package_options: [{ hours: 5, price: 240, label: 'Wide Bay Pack' }] },

  // WA — 4 instructors
  { first_name: 'Jack', last_name: 'Thompson', suburb: 'Subiaco', state: 'WA', postcode: '6008', lat: -31.9475, lng: 115.8247, hourly_rate: 72, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'BMW', vehicle_model: '3 Series', vehicle_year: 2023, languages: ['English'], bio: 'Perth inner-city instructor. Premium service with focus on advanced driving techniques.', years_experience: 8, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Subiaco', 'West Leederville', 'Shenton Park', 'Nedlands', 'Dalkeith'], service_radius_km: 8, adi_registration: 'ADI-WA-505', gender: 'male', familiar_test_centres: ['Welshpool', 'Kelmscott'], package_options: [{ hours: 5, price: 340, label: 'Inner City Pack' }] },
  { first_name: 'Grace', last_name: 'Chen', suburb: 'Canning Vale', state: 'WA', postcode: '6155', lat: -32.0589, lng: 115.9196, hourly_rate: 63, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mazda', vehicle_model: '3', vehicle_year: 2022, languages: ['English', 'Mandarin', 'Cantonese'], bio: 'Perth southern suburbs multilingual instructor. Specialises in international licence conversions.', years_experience: 5, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Canning Vale', 'Willetton', 'Leeming', 'Bull Creek', 'Riverton'], service_radius_km: 10, adi_registration: 'ADI-WA-606', gender: 'female', familiar_test_centres: ['Welshpool', 'Kelmscott'], package_options: [{ hours: 5, price: 300, label: 'Southern Pack' }, { hours: 10, price: 560, label: 'Southern Value' }] },
  { first_name: 'Thomas', last_name: 'Price', suburb: 'Bunbury', state: 'WA', postcode: '6230', lat: -33.3267, lng: 115.6375, hourly_rate: 52, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Holden', vehicle_model: 'Colorado', vehicle_year: 2021, languages: ['English'], bio: 'South West WA instructor covering Bunbury to Busselton. Affordable and friendly service.', years_experience: 9, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Bunbury', 'Busselton', 'Dunsborough', 'Australind', 'Margaret River'], service_radius_km: 25, adi_registration: 'ADI-WA-707', gender: 'male', familiar_test_centres: ['Bunbury', 'Busselton'], package_options: [{ hours: 5, price: 250, label: 'South West Pack' }] },
  { first_name: 'Chloe', last_name: 'Roberts', suburb: 'Rockingham', state: 'WA', postcode: '6168', lat: -32.2813, lng: 115.7277, hourly_rate: 56, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Kia', vehicle_model: 'Rio', vehicle_year: 2022, languages: ['English'], bio: 'Perths southern coastal instructor. Patient with pensioners and nervous first-timers.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Rockingham', 'Waikiki', 'Kwinana', 'Safety Bay', 'Port Kennedy'], service_radius_km: 12, adi_registration: 'ADI-WA-808', gender: 'female', familiar_test_centres: ['Kelmscott', 'Rockingham'], package_options: [{ hours: 5, price: 265, label: 'Coastal Pack' }] },

  // SA — 3 instructors
  { first_name: 'James', last_name: 'White', suburb: 'Prospect', state: 'SA', postcode: '5082', lat: -34.8824, lng: 138.5933, hourly_rate: 62, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Camry', vehicle_year: 2023, languages: ['English'], bio: 'Adelaide northern suburbs instructor. Methodical teaching approach with a focus on road safety.', years_experience: 10, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Prospect', 'Enfield', 'Sefton Park', 'Blair Athol', 'Kilburn'], service_radius_km: 8, adi_registration: 'ADI-SA-404', gender: 'male', familiar_test_centres: ['Adelaide', 'Wingfield'], package_options: [{ hours: 5, price: 295, label: 'Adelaide Pack' }] },
  { first_name: 'Olivia', last_name: 'King', suburb: 'Victor Harbor', state: 'SA', postcode: '5211', lat: -35.5552, lng: 138.6217, hourly_rate: 55, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Hyundai', vehicle_model: 'Accent', vehicle_year: 2022, languages: ['English'], bio: 'Fleurieu Peninsula instructor. Serving Victor Harbor and the surrounding coastal communities.', years_experience: 5, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Victor Harbor', 'Port Elliot', 'Middleton', 'Goolwa', 'Strathalbyn'], service_radius_km: 20, adi_registration: 'ADI-SA-505', gender: 'female', familiar_test_centres: ['Adelaide', 'Mount Barker'], package_options: [{ hours: 5, price: 265, label: 'Fleurieu Pack' }] },
  { first_name: 'Leo', last_name: 'Murphy', suburb: 'Mount Gambier', state: 'SA', postcode: '5290', lat: -37.8278, lng: 140.7716, hourly_rate: 50, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Ford', vehicle_model: 'Fiesta', vehicle_year: 2021, languages: ['English'], bio: 'South East SA instructor covering Mount Gambier and the Limestone Coast region.', years_experience: 11, dual_controls: true, specialises_anxiety: false, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Mount Gambier', 'Millicent', 'Naracoorte', 'Penola', 'Bordertown'], service_radius_km: 25, adi_registration: 'ADI-SA-606', gender: 'male', familiar_test_centres: ['Mount Gambier'], package_options: [{ hours: 5, price: 240, label: 'Limestone Pack' }] },

  // ACT — 2 instructors
  { first_name: 'Emily', last_name: 'Stewart', suburb: 'Woden', state: 'ACT', postcode: '2606', lat: -35.3457, lng: 149.0907, hourly_rate: 65, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Subaru', vehicle_model: 'Forester', vehicle_year: 2023, languages: ['English'], bio: 'South Canberra instructor. Expert in ACT test routes and roundabout navigation.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Woden', 'Phillip', 'Mawson', 'Garran', 'Deakin'], service_radius_km: 10, adi_registration: 'ADI-ACT-303', gender: 'female', familiar_test_centres: ['Canberra', 'Belconnen'], package_options: [{ hours: 5, price: 310, label: 'Woden Pack' }, { hours: 10, price: 580, label: 'Woden Value' }] },
  { first_name: 'Daniel', last_name: 'Ross', suburb: 'Gungahlin', state: 'ACT', postcode: '2912', lat: -35.1843, lng: 149.1344, hourly_rate: 60, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mazda', vehicle_model: '3', vehicle_year: 2022, languages: ['English'], bio: 'North Canberra and Gungahlin instructor. Patient and thorough with learner drivers.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Gungahlin', 'Nicholls', 'Mitchell', 'Forde', 'Bonner'], service_radius_km: 8, adi_registration: 'ADI-ACT-404', gender: 'male', familiar_test_centres: ['Belconnen', 'Canberra'], package_options: [{ hours: 5, price: 290, label: 'Northside Pack' }] },

  // NT — 2 instructors
  { first_name: 'Zoe', last_name: 'Baker', suburb: 'Palmerston', state: 'NT', postcode: '0830', lat: -12.4841, lng: 130.9829, hourly_rate: 58, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Hilux', vehicle_year: 2022, languages: ['English'], bio: 'Greater Darwin instructor. Experienced with wet season driving and unsealed road conditions.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Palmerston', 'Howard Springs', 'Humpty Doo', 'Coolalinga', 'Virginia'], service_radius_km: 20, adi_registration: 'ADI-NT-303', gender: 'female', familiar_test_centres: ['Darwin', 'Palmerston'], package_options: [{ hours: 5, price: 275, label: 'Palmerston Pack' }] },
  { first_name: 'Liam', last_name: 'Cox', suburb: 'Katherine', state: 'NT', postcode: '0850', lat: -14.4651, lng: 132.2630, hourly_rate: 52, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Mitsubishi', vehicle_model: 'Triton', vehicle_year: 2021, languages: ['English'], bio: 'Big Riverside region instructor. Serving Katherine and remote NT communities.', years_experience: 8, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Katherine', 'Mataranka', 'Kununurra', 'Pine Creek', 'Larrimah'], service_radius_km: 30, adi_registration: 'ADI-NT-404', gender: 'male', familiar_test_centres: ['Katherine'], package_options: [{ hours: 5, price: 250, label: 'Big Rivers Pack' }] },

  // TAS — 2 instructors
  { first_name: 'Ella', last_name: 'Morgan', suburb: 'Sandy Bay', state: 'TAS', postcode: '7005', lat: -42.8957, lng: 147.3344, hourly_rate: 64, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Kia', vehicle_model: 'Cerato', vehicle_year: 2022, languages: ['English'], bio: 'Greater Hobart instructor. Calm and patient with nervous drivers on Tassies winding roads.', years_experience: 7, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Sandy Bay', 'Taroona', 'Kingston', 'Margate', 'Huonville'], service_radius_km: 15, adi_registration: 'ADI-TAS-404', gender: 'female', familiar_test_centres: ['Hobart', 'Kingston'], package_options: [{ hours: 5, price: 305, label: 'Hobart South' }] },
  { first_name: 'Charlie', last_name: 'Hill', suburb: 'Burnie', state: 'TAS', postcode: '7320', lat: -41.0533, lng: 145.9036, hourly_rate: 50, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Suzuki', vehicle_model: 'Swift', vehicle_year: 2021, languages: ['English'], bio: 'North-West Coast Tasmania instructor. Affordable lessons covering Burnie to Wynyard.', years_experience: 10, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], service_suburbs: ['Burnie', 'Wynyard', 'Somerset', 'Cooee', 'Parklands'], service_radius_km: 15, adi_registration: 'ADI-TAS-505', gender: 'male', familiar_test_centres: ['Burnie'], package_options: [{ hours: 5, price: 240, label: 'NW Pack' }] },

  // NSW extra — 1 more
  { first_name: 'Ruby', last_name: 'Singh', suburb: 'Blacktown', state: 'NSW', postcode: '2148', lat: -33.7703, lng: 150.9049, hourly_rate: 58, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Nissan', vehicle_model: 'Pulsar', vehicle_year: 2022, languages: ['English', 'Hindi', 'Punjabi'], bio: 'Western Sydney instructor serving diverse communities. Multilingual lessons available.', years_experience: 6, dual_controls: true, specialises_anxiety: true, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], service_suburbs: ['Blacktown', 'Mount Druitt', 'Doonside', 'Seven Hills', 'Lalor Park'], service_radius_km: 10, adi_registration: 'ADI-NSW-121', gender: 'female', familiar_test_centres: ['Seven Hills', 'Penrith'], package_options: [{ hours: 5, price: 275, label: 'Western Sydney Pack' }] },

  // VIC extra — 1 more
  { first_name: 'Max', last_name: 'Hamilton', suburb: 'Frankston', state: 'VIC', postcode: '3199', lat: -38.1421, lng: 145.1218, hourly_rate: 60, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Toyota', vehicle_model: 'Corolla', vehicle_year: 2022, languages: ['English'], bio: 'Mornington Peninsula instructor covering Frankston to Hastings. Great with all skill levels.', years_experience: 8, dual_controls: true, specialises_anxiety: true, accepts_international: false, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Frankston', 'Mordialloc', 'Chelsea', 'Mount Eliza', 'Seaford'], service_radius_km: 15, adi_registration: 'ADI-901011', gender: 'male', familiar_test_centres: ['Dandenong', 'Carlton'], package_options: [{ hours: 5, price: 285, label: 'Peninsula Pack' }, { hours: 10, price: 520, label: 'Peninsula Value' }] },

  // QLD extra — 1 more
  { first_name: 'Aria', last_name: 'Patel', suburb: 'Indooroopilly', state: 'QLD', postcode: '4068', lat: -27.4970, lng: 152.9732, hourly_rate: 70, transmission: 'both', licence_types: ['car'], lesson_duration_mins: 60, vehicle_make: 'Honda', vehicle_model: 'HR-V', vehicle_year: 2023, languages: ['English', 'Hindi', 'Gujarati'], bio: 'Brisbane western suburbs instructor. Expert test preparation with a calm teaching approach.', years_experience: 7, dual_controls: true, specialises_anxiety: false, accepts_international: true, availability_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], service_suburbs: ['Indooroopilly', 'Taringa', 'St Lucia', 'Chapel Hill', 'Kenmore'], service_radius_km: 10, adi_registration: 'ADI-QLD-777', gender: 'female', familiar_test_centres: ['Greenslopes', 'Chermside'], package_options: [{ hours: 5, price: 330, label: 'Western Brisbane' }, { hours: 10, price: 620, label: 'Western Brisbane Value' }] },
];

const reviewTemplates = [
  { reviewer: 'Tom S.', rating: 5, patience: 5, comms: 5, value: 4, punctuality: 5, pass: 'passed_first' as const, text: 'Amazing instructor! Very patient and helped me pass first time.' },
  { reviewer: 'Emma W.', rating: 4, patience: 4, comms: 5, value: 4, punctuality: 5, pass: 'passed_first' as const, text: 'Great instructor, really helped with my parallel parking technique.' },
  { reviewer: 'Jack R.', rating: 5, patience: 5, comms: 5, value: 5, punctuality: 5, pass: 'passed_first' as const, text: 'Couldn\'t have asked for a better instructor. Highly recommend.' },
  { reviewer: 'Olivia P.', rating: 4, patience: 5, comms: 4, value: 3, punctuality: 4, pass: 'passed_retry' as const, text: 'Really helped me overcome my nerves after failing my first test.' },
  { reviewer: 'Liam N.', rating: 5, patience: 4, comms: 5, value: 5, punctuality: 5, pass: 'passed_first' as const, text: 'Professional, knowledgeable, and made the whole process really easy.' },
  { reviewer: 'Sophie M.', rating: 4, patience: 5, comms: 4, value: 4, punctuality: 4, pass: 'still_learning' as const, text: 'Still learning but feeling much more confident behind the wheel.' },
  { reviewer: 'Noah K.', rating: 5, patience: 5, comms: 5, value: 5, punctuality: 5, pass: 'passed_first' as const, text: 'Best driving instructor. No question.' },
  { reviewer: 'Mia C.', rating: 4, patience: 4, comms: 4, value: 4, punctuality: 5, pass: 'passed_retry' as const, text: 'Very thorough and made sure I was ready before booking my test.' },
  { reviewer: 'Ethan B.', rating: 5, patience: 5, comms: 5, value: 5, punctuality: 4, pass: 'passed_first' as const, text: 'Fantastic experience from start to finish. Highly skilled instructor.' },
  { reviewer: 'Ava L.', rating: 4, patience: 4, comms: 5, value: 4, punctuality: 5, pass: 'passed_first' as const, text: 'Clear instructions and very patient. Made learning enjoyable.' },
];

function slugify(first: string, last: string, suburb: string) {
  return `${first.toLowerCase()}-${last.toLowerCase().replace(/'/, '')}-${suburb.toLowerCase().replace(/\s+/g, '-')}`;
}

export async function GET() {
  if (!supabase) {
    return NextResponse.json({ error: 'Supabase not configured' }, { status: 500 });
  }

  const results: { instructor: string; status: string; error?: string }[] = [];

  for (const inst of instructors) {
    const slug = slugify(inst.first_name, inst.last_name, inst.suburb);

    const { error } = await supabase.from('instructors').insert({
      slug,
      ...inst,
      is_claimed: false,
      is_verified: true,
      profile_completeness: 100,
    });

    if (error) {
      results.push({ instructor: `${inst.first_name} ${inst.last_name}`, status: 'error', error: error.message });
      continue;
    }

    const { data: inserted } = await supabase.from('instructors').select('id').eq('slug', slug).single();

    if (inserted) {
      const selectedReviews = reviewTemplates.sort(() => Math.random() - 0.5).slice(0, 3 + Math.floor(Math.random() * 5));
      for (const r of selectedReviews) {
        await supabase.from('reviews').insert({
          instructor_id: inserted.id,
          reviewer_name: r.reviewer,
          reviewer_email: `${r.reviewer.toLowerCase().replace(/\s/, '')}@example.com`,
          rating_overall: r.rating,
          rating_patience: r.patience,
          rating_communication: r.comms,
          rating_value: r.value,
          rating_punctuality: r.punctuality,
          pass_outcome: r.pass,
          review_text: r.text,
          is_approved: true,
        });
      }
    }

    results.push({ instructor: `${inst.first_name} ${inst.last_name} (${inst.suburb}, ${inst.state})`, status: 'inserted' });
  }

  const inserted = results.filter((r) => r.status === 'inserted').length;
  const failed = results.filter((r) => r.status === 'error').length;

  return NextResponse.json({
    message: `Seeded ${inserted} new Australian instructors (${failed} failed).`,
    total: inserted,
    failed,
    results,
  });
}
